# Generated by Django 3.1.7 on 2021-04-01 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=32, verbose_name='设施名字')),
            ],
            options={
                'db_table': 'tb_facility',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('price', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=512)),
                ('room_count', models.IntegerField(default=1)),
                ('acreage', models.IntegerField(default=0)),
                ('unit', models.CharField(default='', max_length=32)),
                ('capacity', models.IntegerField(default=1)),
                ('beds', models.CharField(default='', max_length=64)),
                ('deposit', models.IntegerField(default=0)),
                ('min_days', models.IntegerField(default=1)),
                ('max_days', models.IntegerField(default=0)),
                ('order_count', models.IntegerField(default=0)),
                ('index_image_url', models.CharField(default='', max_length=256)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.area', verbose_name='归属地的地区编号')),
                ('facility', models.ManyToManyField(to='homes.Facility', verbose_name='和设施表之间多对多的关系')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL, verbose_name='房屋主人的用户编号')),
            ],
            options={
                'db_table': 'tb_house',
            },
        ),
    ]
